services:
    con4gis.auth.listener.interactive.login:
        class: con4gis\AuthBundle\Classes\Listener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin, priority: 1000 }

    con4gis.auth.listener.login.failure:
        class: con4gis\AuthBundle\Classes\Listener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onLoginFailure, priority: 10 }